name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]
env:
  REACT_APP_FIREBASE_KEY: ${{secrets.REACT_APP_FIREBASE_KEY}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build 🔧
        run: |
          yarn install
          yarn run lint:js
          yarn run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
